name: CI
on: push
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Login to prefect cloud
        run: prefect cloud login --key ${{ secrets.PREFECT_API_KEY }} --workspace "chrisca/default"
      - name: deploy
        run: python deploy.py ${{steps.meta.outputs.tags }}
          
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{steps.meta.outputs.tags }}
